"""usuarios con auth

Revision ID: bfc586aecf3a
Revises: f0a65b947021
Create Date: 2026-09-22 13:39:24.480365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc586aecf3a'
down_revision: Union[str, Sequence[str], None] = 'f0a65b947021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('items_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    # Primero eliminamos la FK y las columnas viejas de productos que dependen de categorias
    op.drop_constraint('productos_categoria_id_fkey', 'productos', type_='foreignkey')
    op.drop_column('productos', 'en_stock')
    op.drop_column('productos', 'categoria_id')
    op.drop_column('productos', 'precio')
    # Ahora sí podemos borrar categorias sin dependencias
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # Agregar columnas nuevas a productos
    op.add_column('productos', sa.Column('precio_final', sa.Float(), nullable=False, server_default='0'))
    op.add_column('productos', sa.Column('cuotas_cantidad', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('productos', sa.Column('cuotas_valor', sa.Float(), nullable=False, server_default='0'))
    op.add_column('productos', sa.Column('garantia_meses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('productos', sa.Column('stock', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos', if_exists=True)
    op.add_column('usuarios', sa.Column('rol', sa.String(), nullable=True, server_default='customer'))
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(), nullable=True))
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_column('usuarios', 'rol')
    op.add_column('productos', sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('en_stock', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('productos_categoria_id_fkey'), 'productos', 'categorias', ['categoria_id'], ['id'])
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('productos', 'stock')
    op.drop_column('productos', 'garantia_meses')
    op.drop_column('productos', 'cuotas_valor')
    op.drop_column('productos', 'cuotas_cantidad')
    op.drop_column('productos', 'precio_final')
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categorias_pkey'))
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
